version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
      - redis
    ports:
      - 3001:3001
    networks:
      - aibot-network

  frontend:
      image: aibot-next  # 本地构建的前端镜像
      ports:
        - 3000:3000 
      networks:
        - aibot-network 
  mysql:
    image: mysql:8.4.3
    ports:
        - 3306:3306 
    volumes:
      - ~/mysql/mysqlbak:/home/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_qaqxxxl4
      MYSQL_DATABASE: aibot
      MYSQL_TMP_TABLE_SIZE: 64M
      MYSQL_INNODB_BUFFER_POOL_SIZE: 128M
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      MYSQL_MAJOR: 8.4
      MYSQL_VERSION: 8.4.3-1.el9
      MYSQL_SHELL_VERSION: 8.4.3-1.el9
    networks:
      - aibot-network

  redis:
    image: redis:7
    ports:
      - 6379:6379 
    # volumes:
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    networks:
      - aibot-network

  nginx:
    image: nginx:stable-alpine # 指定服务镜像
    container_name: nginx # 容器名称
    restart: always # 重启方式
    ports: # 映射端口
      - 8000:80
    volumes: # 挂载数据卷
      - ~/www/aibot/nginx/conf.d:/etc/nginx/conf.d
      - ~/www/aibot/nginx/logs:/var/log/nginx
      - ~/www/aibot/nginx/cert:/etc/nginx/cert
    depends_on: # 启动顺序
      - nest-app
      - frontend
    networks:
      - aibot-network
    

networks:
  aibot-network:
    driver: bridge
